// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqZUp-WFfAz1WmZikBzJJb8xcCNT67UcY',
    appId: '1:270549215024:web:6c416fc9183214db6d8af5',
    messagingSenderId: '270549215024',
    projectId: 'image-ai-e609e',
    authDomain: 'image-ai-e609e.firebaseapp.com',
    storageBucket: 'image-ai-e609e.appspot.com',
    measurementId: 'G-YJJTPWW4F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmTywTZWB6tuzTJfpLQ-hMNoCdfgGB3YA',
    appId: '1:270549215024:android:7a7025748e94404d6d8af5',
    messagingSenderId: '270549215024',
    projectId: 'image-ai-e609e',
    storageBucket: 'image-ai-e609e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB20akfOudsMF9NX9VtjW4ffqYyk9IDIq0',
    appId: '1:270549215024:ios:58184df8ad34631c6d8af5',
    messagingSenderId: '270549215024',
    projectId: 'image-ai-e609e',
    storageBucket: 'image-ai-e609e.appspot.com',
    iosBundleId: 'com.example.loginapp',
  );
}
